export enum SocketEvents {
	JOIN = 'join',
	LEAVE = 'leave',
	CONNECTION = 'connection',
	ROOM_ENTER = 'roomEnter',
	ROOM_LEAVE = 'roomLeave',
	MESSAGE_GET = 'messageGet',
	MESSAGE_SEND = 'messageSend',
	TYPING = 'typing',
	IS_TYPING = 'isTyping',
	DISCONNECT = 'disconnect',
	NOTIFICATION = 'notification',
	QUESTION = 'question',
	ANSWER = 'answer',
	RESULT = 'result',
	START_GAME = 'startGame',
	STARTING = 'starting',
	END_GAME = 'endGame',
	RESULTS = 'results',
	GET_GAMES = 'getGames',
	OPEN_GAMES = 'openGames',
	ERROR = 'error',
}
